services:
  connect:
    image: confluentinc/cp-kafka-connect:latest
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "host.docker.internal:9093"
      CONNECT_SECURITY_PROTOCOL: "SSL"
      CONNECT_SSL_TRUSTSTORE_LOCATION: "/etc/kafka-connect/certs/truststore.jks"
      CONNECT_SSL_TRUSTSTORE_PASSWORD: "changeit"
      CONNECT_GROUP_ID: "kafka-connect-group"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-status"
      CONNECT_REST_ADVERTISED_HOST_NAME: "localhost"
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_PORT: 8083
      CONNECT_PLUGIN_PATH: /usr/share/java,/etc/kafka-connect/jars
    volumes:
      - ./certs:/etc/kafka-connect/certs
      - ./jars:/etc/kafka-connect/jars
      - ./data-duckdb:/data
    ports:
      - "8083:8083"
