version: "3.9"

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
    volumes:
      - ./minio-data:/data
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Web Console
    restart: unless-stopped
